---
- name: Install golang
  hosts: all
  remote_user: ubuntu
  vars:
    ansible_ssh_private_key: "~/.ssh/github_actions"

  tasks:
  - name: Install golang from yum
    ansible.builtin.apt:
      name: golang
      state: latest