---
- name: Install golang
  hosts: all
  remote_user: ubuntu
  vars:
    ansible_ssh_private_key: "~/.ssh/github_actions"

  tasks:
  - name: Install golang from yum
    become: true
    ansible.builtin.apt:
      name: golang
      state: latest
  - name: Create a directory if it does not exist
    become: true
    ansible.builtin.file:
      path: /etc/tidus/
      state: directory
      mode: '0755'
  - name: Copy pkg with owner and permissions
    become: true
    ansible.builtin.copy:
      src: ./tidus-api
      dest: /etc/tidus/tidus-api
      owner: ubuntu
      group: ubuntu
      mode: '0744'
  - name: Copy service file with owner and permissions
    become: true
    ansible.builtin.copy:
      src: ./tidus.service
      dest: /etc/systemd/system/tidus.service
      owner: ubuntu
      group: ubuntu
      mode: '0744'